### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by TheDiamondYT1** [davidgfnet/micro-web-server#1]
Can you add me to the repository so i can create a release so i can submit a PR to the [termux-packages](https://github.com/termux/termux-packages) repo so this wonderful lightweight webserver can be available on Android.

Also on most systems ports below **1024** are consided "privileged" so th default port should be `8080` or something.

**EDIT:** And can you tell me what version this is?

**Comment by davidgfnet** [comment]
Sounds good. I'm doing a bit of a cleanup at the moment, I'll come back in a week or so after vacation :D

**Comment by davidgfnet** [comment]
Hey Luke, I think I'm more or less done so far with the cleanup. What exactly do you need to do? Cheers!

**Comment by TheDiamondYT1** [comment]
I need you to make a release or give me a direct link to a tar.gz/.xz file so that it can be submitted to the termux package repository.

If this is already in a linux apt repository somewhere, could i have the link to that instead?

**Comment by davidgfnet** [comment]
Hey Luke, sorry I forgot about this issue. Will creating a release in github help you? That should create a tar.gz file in Downloads.

**Comment by TheDiamondYT1** [comment]
@davidgfnet Yes, please that will help.

**Comment by davidgfnet** [comment]
I added two binary targets in the Makefile, one of them is bigger cause it has a proxy mode and comes with a DNS resolver. You might want to use the smaller one that just servers as HTTP server.
Do I need to include any install rule?

**Comment by TheDiamondYT1** [comment]
Im not very good with Makefiles... I managed to get this working by litterally cloning the repo and running make on my android so just create a release with the source code i dont need any binaries.

**Comment by davidgfnet** [comment]
There you go: https://github.com/davidgfnet/micro-web-server/archive/v1.0.0.tar.gz
